package com.taller.auth;
import com.taller.security.JwtService; import com.taller.user.*; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import org.springframework.http.*; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.web.bind.annotation.*; import org.springframework.web.server.ResponseStatusException; import java.time.*; import java.time.temporal.ChronoUnit; import java.util.*;
@RestController @RequestMapping("/api/auth") public class AuthController {
 private final UserRepository users; private final PasswordEncoder encoder; private final JwtService jwt; public AuthController(UserRepository u,PasswordEncoder e,JwtService j){users=u;encoder=e;jwt=j;}
 record Registro(@NotBlank String nombre,@Email @NotBlank String email,@Size(min=8,message="La contraseña debe tener al menos 8 caracteres") String password){} record Login(@Email @NotBlank String email,@NotBlank String password){} record Recuperar(@Email @NotBlank String email){} record Restablecer(@NotBlank String token,@Size(min=8) String password){} record Respuesta(String token,String nombre,Role rol){}
 @PostMapping("/register") @ResponseStatus(HttpStatus.CREATED) Respuesta registrar(@Valid @RequestBody Registro r){ if(users.findByEmailIgnoreCase(r.email()).isPresent())throw new ResponseStatusException(HttpStatus.CONFLICT,"El correo ya está registrado"); User u=new User();u.setNombre(r.nombre());u.setEmail(r.email().toLowerCase());u.setPassword(encoder.encode(r.password()));u.setRol(Role.CLIENTE);users.save(u);return new Respuesta(jwt.token(u),u.getNombre(),u.getRol()); }
 @PostMapping("/login") Respuesta login(@Valid @RequestBody Login l){User u=users.findByEmailIgnoreCase(l.email()).filter(User::isActivo).filter(x->encoder.matches(l.password(),x.getPassword())).orElseThrow(()->new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Correo o contraseña incorrectos"));return new Respuesta(jwt.token(u),u.getNombre(),u.getRol());}
 @PostMapping("/forgot-password") Map<String,String> olvidar(@Valid @RequestBody Recuperar r){users.findByEmailIgnoreCase(r.email()).ifPresent(u->{u.setTokenRecuperacion(UUID.randomUUID().toString());u.setTokenExpira(Instant.now().plus(30,ChronoUnit.MINUTES));users.save(u); /* Integrar aquí envío por correo; nunca exponer el token fuera del entorno de desarrollo. */});return Map.of("message","Si el correo existe, recibirás instrucciones para recuperar tu cuenta.");}
 @PostMapping("/reset-password") Map<String,String> reset(@Valid @RequestBody Restablecer r){User u=users.findByTokenRecuperacion(r.token()).filter(x->x.getTokenExpira().isAfter(Instant.now())).orElseThrow(()->new ResponseStatusException(HttpStatus.BAD_REQUEST,"El enlace es inválido o expiró"));u.setPassword(encoder.encode(r.password()));u.setTokenRecuperacion(null);u.setTokenExpira(null);users.save(u);return Map.of("message","Contraseña actualizada correctamente");}
}
