import { createApp } from 'vue/dist/vue.esm-bundler.js'
import './style.css'
const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:8081/api'
createApp({
  data:()=>({vista:'login',nombre:'',email:'',password:'',confirmacion:'',mensaje:'',error:'',cargando:false,usuario:JSON.parse(localStorage.getItem('usuario')||'null')}),
  methods:{
    async enviar(ruta,cuerpo){const res=await fetch(`${API_URL}/auth/${ruta}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(cuerpo)});const data=await res.json();if(!res.ok)throw new Error(data.message||'No fue posible completar la operación');return data},
    async login(){this.limpiar();this.cargando=true;try{this.sesion(await this.enviar('login',{email:this.email,password:this.password}))}catch(e){this.error=e.message}finally{this.cargando=false}},
    async registro(){this.limpiar();if(this.password!==this.confirmacion){this.error='Las contraseñas no coinciden';return}this.cargando=true;try{this.sesion(await this.enviar('register',{nombre:this.nombre,email:this.email,password:this.password}))}catch(e){this.error=e.message}finally{this.cargando=false}},
    async recuperar(){this.limpiar();this.cargando=true;try{this.mensaje=(await this.enviar('forgot-password',{email:this.email})).message}catch(e){this.error=e.message}finally{this.cargando=false}},
    sesion(d){this.usuario={nombre:d.nombre,rol:d.rol,token:d.token};localStorage.setItem('usuario',JSON.stringify(this.usuario));this.mensaje='¡Bienvenido! Sesión iniciada correctamente.'},salir(){localStorage.removeItem('usuario');this.usuario=null;this.vista='login';this.limpiar()},limpiar(){this.error='';this.mensaje=''}
  },
  template:`<main><section class="hero"><div class="marca"><span class="tuerca">⚙</span><span>TORQUE<span class="azul">PRO</span></span></div><div class="hero-text"><p class="etiqueta">TALLER MECÁNICO</p><h1>Tu vehículo<br><em>en buenas manos.</em></h1><p>Gestiona tus órdenes de reparación con confianza, claridad y control.</p><div class="puntos"><span>✓ Atención segura</span><span>✓ Seguimiento en tiempo real</span></div></div><div class="auto">🚙</div></section><section class="panel"><div v-if="usuario" class="bienvenida"><div class="icono-grande">✓</div><p class="etiqueta">SESIÓN ACTIVA</p><h2>Hola, {{usuario.nombre}}</h2><p>Has ingresado como <b>{{usuario.rol}}</b>.</p><button @click="salir">Cerrar sesión</button></div><form v-else @submit.prevent="vista==='login'?login():vista==='registro'?registro():recuperar()"><div class="form-head"><p class="etiqueta">BIENVENIDO</p><h2>{{vista==='login'?'Inicia sesión':vista==='registro'?'Crea tu cuenta':'Recupera tu acceso'}}</h2><p>{{vista==='recuperar'?'Escribe tu correo y te enviaremos instrucciones.':vista==='registro'?'Regístrate para consultar las reparaciones de tu vehículo.':'Ingresa tus datos para continuar.'}}</p></div><label v-if="vista==='registro'">Nombre completo<input v-model="nombre" required placeholder="Tu nombre"></label><label>Correo electrónico<input v-model="email" required type="email" placeholder="nombre@correo.com"></label><label v-if="vista!=='recuperar'">Contraseña<input v-model="password" required type="password" minlength="8" placeholder="••••••••"></label><label v-if="vista==='registro'">Confirmar contraseña<input v-model="confirmacion" required type="password" minlength="8" placeholder="••••••••"></label><button :disabled="cargando">{{cargando?'Procesando…':vista==='login'?'Ingresar':'Continuar'}} <span>→</span></button><p v-if="error" class="alerta error">{{error}}</p><p v-if="mensaje" class="alerta ok">{{mensaje}}</p><div class="enlaces"><a v-if="vista==='login'" @click="vista='recuperar';limpiar()">¿Olvidaste tu contraseña?</a><a v-if="vista==='login'" @click="vista='registro';limpiar()">Crear una cuenta</a><a v-if="vista!=='login'" @click="vista='login';limpiar()">← Volver a iniciar sesión</a></div></form><p class="pie">🔒 Tus datos están protegidos</p></section></main>`
}).mount('#app')
